method: fundiff
dataset: ccs
model:
  channels: [x]
  resolution: [64, 200]
normalization:
  channels: [x]
  mean: [248.86085613126085]
  std: [212.11948744691105]
  scale: 0.5
sampling:
  num_steps: 100
  decode_chunk: 2048
guidance:
  type: conditional_rectified_flow
  observed_field: y
  observation_operator: sparse_points
  condition_representation: sparse_masked_grid
  num_sensors: 128
  condition_normalization:
    channels: [y]
    mean: [0.08489088577079608]
    std: [0.21714609039354066]
    scale: 0.5
postprocess: {}
