method: fundiff
dataset: light_transport
model:
  channels: [sigma_t1, sigma_t2]
  resolution: 64
normalization:
  channels: [sigma_t1, sigma_t2]
  mean: [2.5167187795048154, 2.517986240638265]
  std: [1.756092760094968, 1.7550055063328003]
  scale: 0.5
sampling:
  num_steps: 20
  decode_chunk: 1024
guidance:
  pending: false
  type: conditional_rectified_flow
  observed_field: u
  observation_operator: area_average
  condition_representation: area_average_repeat
  condition_low_resolution: 16
  condition_normalization:
    channels: [u]
    mean: [0.3229744808981993]
    std: [0.13083477812502864]
    scale: 0.5
postprocess: {}
